services:
  app:
    container_name: laravel-docker-postgres-app
    build:
      context: .
      target: php
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:8000
    networks:
      - laravel-docker-postgres-app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: laravel-docker-postgres-db
    restart: always
    environment:
      POSTGRES_DB: laravel-docker-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - laravel-docker-postgres-app

networks:
  laravel-docker-postgres-app:

volumes:
  db_data: